# Site Info
title:              "The Plain"
description:        "A minimalist Jekyll theme"
author_name:        "cflag" # change this to your name
logo_url:           https://cflag.io/assets/1559181471128.gif

# Site Settings
url:                https://cflag.io # main url
baseurl:            /
permalink:          /:title # Post permalink
timezone:           America/Denver # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
